name: fsdl-text-recognizer-2022
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10  # versioned to match Google Colab  # version also pinned in Dockerfile
  - pytorch-cuda=11.8  # versioned to match Google Colab
  - pip=23.1.2  # versioned to match Google Colab  # version also pinned in Dockerfile
